Luchkin_Fedor_IU6_31b_zach_work/config/routes.rb
Rails.application.routes.draw do
  # scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users

    root 'tasks#index' # controller - action
    get 'tasks/index'

    delete 'tasks/destroy_all_done'

    put 'tasks/clear_all_done'

    get 'tasks/index_subj'
    get 'tasks/index_deadline'
    get 'tasks/index_cleared'
    get 'tasks/index_all'

    resources :tasks do
      put :complete, on: :member
      put :uncomplete, on: :member
      put :complete_in_deadline, on: :member
      put :complete_in_subj, on: :member
      put :uncomplete_in_subj, on: :member
      put :return_done, on: :member
    end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
      #end
end

Luchkin_Fedor_IU6_31b_zach_work/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Luchkin_Fedor_IU6_31b_zach_work/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :subj, :descript, :deadline, :user_id, presence: true
  after_initialize :set_defaults

  def complete!
    self.status = true
    save
  end

  def uncomplete!
    self.status = false
    save
  end

  def clear!
    self.hidden = true
    save
  end

  def un_clear!
    self.hidden = false
    save
  end

  private
  def set_defaults
    self.hidden = false if self.new_record?
    #self.status = false if self.new_record?
    #self.deadline = Date.today if self.new_record?
  end
end

Luchkin_Fedor_IU6_31b_zach_work/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks

  validates :email, presence: true
  validates_associated :tasks
  validates :password, length: { in: 6..30 }
  validates :email, uniqueness: true
end

Luchkin_Fedor_IU6_31b_zach_work/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

Luchkin_Fedor_IU6_31b_zach_work/app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy complete uncomplete complete_in_subj uncomplete_in_subj complete_in_deadline return_done]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @completed_tasks = Task.where(status: true).where(hidden: false).order('updated_at')
    @uncompleted_tasks = Task.where(status: false).order('created_at')
    @cleared_tasks = Task.where(hidden: true).order('updates_at')
  end

  def index_subj
    @tasks = Task.where(hidden: false).order('subj').order('status')
    # @uncompleted_tasks = Task.where(status: false).order('subj')
    # @completed_tasks = Task.where(status: true).where(hidden: false).order('subj')
  end

  def index_deadline
    @uncompleted_tasks = Task.where(status: false).order('deadline')
  end

  def index_cleared
    @cleared_tasks = Task.where(hidden: true).order('updated_at')
  end

  def index_all
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks
  # POST /tasks.json
  def create
    if user_signed_in?
      @task = current_user.tasks.new(task_params)
      respond_to do |format|
        if @task.save
          format.html { redirect_to @task, notice: 'Задача успешно создана.' }
          format.json { render :show, status: :created, location: @task }
        else
          format.html { render :new }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_user_session_path
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Задача успешно бобновлена.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Задача успешно удалена.' }
      format.json { head :no_content }
    end
  end

  def complete
    @task.complete!
    redirect_to tasks_path
  end

  def uncomplete
    @task.uncomplete!
    redirect_to tasks_path
  end

  def complete_in_subj
    @task.complete!
    redirect_to tasks_index_subj_path
  end

  def uncomplete_in_subj
    @task.uncomplete!
    redirect_to tasks_index_subj_path
  end

  def complete_in_deadline
    @task.complete!
    redirect_to tasks_index_deadline_path
  end

  def destroy_all_done
    @cleared_tasks = Task.where(status: true).where(hidden: true).order('updated_at')
    @cleared_tasks.each(&:destroy)
    redirect_to tasks_path, notice: 'Выполненные задачи успешно удалены.'
  end

  def clear_all_done
    # @cleared_tasks = Task.where(hidden: true).order('updates_at')
    @completed_tasks = Task.where(status: true).order('updated_at')
    @completed_tasks.each(&:clear!)
    redirect_to tasks_path, notice: 'Выполненные задачи перемещены в архив завершенных.'
  end

  def return_done
    @task.un_clear!
    redirect_to tasks_index_cleared_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

    def task_params
    params.require(:task).permit(:subj, :descript, :status, :user_id, :deadline, :hidden)
  end
end

Luchkin_Fedor_IU6_31b_zach_work/app/helpers/application_helper.rb
module ApplicationHelper
end

Luchkin_Fedor_IU6_31b_zach_work/app/helpers/tasks_helper.rb
module TasksHelper
end

Luchkin_Fedor_IU6_31b_zach_work/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ROCK AND STONE!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-dark flex-column flex-md-row bd-navbar sticky-top">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div><p class="alert alert-dark bg-dark text-warning font-weight-bold" >ROCK AND STONE 🤘</p></div>
        <div><p class="text-dark">ffffff</p></div>           
        <div class="btn-group mr-auto">
    <!--  <li class="nav-item active">
            <a class="nav-link text-white" href="/"><%= t('layouts.application.nav_1') %><span class="sr-only">(current)</span></a>
          </li>   -->

    <!--  <li class="nav-item active">
            <a class="nav-link text-white" href="/tasks/index_subj"><%= t('.nav_2') %><span class="sr-only">(current)</span></a>
          </li>   -->
          <%= link_to "#{t('layouts.application.nav_1')}", tasks_path(@tasks), method: :get, class: 'btn btn-outline-dark text-black', style: 'background-color: #FBB103' %>
          <%= link_to "#{t('.nav_2')}", tasks_index_subj_path(@tasks), method: :get, class: 'btn btn-outline-dark text-black', style: 'background-color: #FBB103' %>
          <%= link_to "#{t('.nav_3')}", tasks_index_deadline_path(@tasks), method: :get, class: 'btn btn-outline-dark text-black', style: 'background-color: #FBB103' %>
          <%= link_to "#{t('.nav_4')}", tasks_index_cleared_path(@tasks), method: :get, class: 'btn btn-outline-dark text-black', style: 'background-color: #FBB103' %>
          <%= link_to "#{t('.nav_5')}", tasks_index_all_path(@tasks), method: :get, class: 'btn btn-outline-dark text-black', style: 'background-color: #FBB103' %>          
        </div>            
        <span class="alert alert-warning text-dark mt bg-warning"><%= t('.today_date') %> <%= Date.today %></span>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-info" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= t('.lang') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'English',  {locale: :en}, class: "dropdown-item" %>
            <%= link_to 'Русский',  {locale: :ru}, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Others</a>
          </div>
        </div>
        <div class="">
          <% if !user_signed_in? %>
            <%= link_to "#{t('.login')}",  new_user_session_path, class: "btn btn-outline-warning btn-sm" %>
            <%= link_to "#{t('.sign_up')}", new_user_registration_path, class: "btn btn-outline-info btn-sm" %>
          <% else %>
            <%= link_to "#{t('.edit_user')}", edit_user_registration_path, class: "btn btn-outline-warning btn-sm" %>
            <%= link_to "#{t('.sign_out')}",  destroy_user_session_path, method: :delete, class: "btn btn-outline-info btn-sm" %>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <!-- тут можно побаловаться с <div class="row"></div>   -->
      <%= yield %>
    </div>

  </body>
</html>

Luchkin_Fedor_IU6_31b_zach_work/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="alert alert bg-warning text-dark col-md-10"> <%= t('tasks.index.head') %> </h1>
<div class="container sticky-top" style="top: 70px">
  <% if user_signed_in? %>
    <div class="row">
      <%= link_to "#{t('.new_task')}", new_task_path, class: 'btn btn-success btn-lg col-md-7 mt-4 mb-5' %>
      <%= link_to "#{t('.clear_all_done')}", tasks_clear_all_done_path(@tasks), method: :put, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-lg col-md-3 mt-4 mb-5' %>
      <% activity_btn = '' %>
    </div>
  <% else %>
    <p class="alert alert bg-dark text-warning col-md-10" ><b><%= t('.login_to') %></b></p>
    <% activity_btn = 'disabled' %>
  <% end %>
</div>

<table class="table table-hover mb-4 col-md-10">
  <% if @uncompleted_tasks.count > 0 %>
    <thead>
    <tr style="background-color: rgba(255,192,45,1)">
      <th class="text-center" scope="col">№</th>
      <th class="text-center" scope="col"><%= t('.subj') %></th>
      <th class="text-center" scope="col"><%= t('.hometask') %></th>
      <th class="text-center" scope="col"><%= t('.deadline') %></th>
      <th colspan="3" class="text-center" scope="col"><%= t('.actions') %></th>
      <th class="" scope="col"><%= t('.completed') %></th>
    </tr>
    </thead>

    <tbody>
  <% end %>
  <% num = 0 %>

  <% @uncompleted_tasks.each do |task| %>


    <% if (task.deadline - Date.today) <0 %>
      <% color = '#000000' %>
      <% stilyok = 'font-weight-bold' %>
    <% else %>
      <% if (task.deadline - Date.today) <=3  %>
        <% color = '#b60800' %>
      <% else %>
        <% if (task.deadline - Date.today) <= 10 %>
          <% color = '#ff842b' %>
        <% else %>
          <% color = '#00b200' %>
        <% end %>
      <% end %>
    <% end %>

    <tr class="task">
      <th scope="row"><p style="color:<%= color %>"><%= num += 1%></p></th>
      <td><p style="color:<%= color %>"><u><%= task.subj  %></u></p></td>
      <td><pre style="color:<%= color %>"> <%= task.descript %></pre></td>
      <td class="action"><p class="<%=stilyok%>" style="color:<%= color %>"><%= task.deadline %></p></td>
      <td><%= link_to "#{t('.show')}", task, class: 'action btn btn-light btn-sm ml-4' %></td>
      <td><%= link_to "#{t('.edit')}", edit_task_path(task), class: "btn btn-outline-warning btn-sm #{activity_btn}" %></td>
      <td><%= link_to "#{t('.delete')}", task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm #{activity_btn}" %></td>
      <td><%= link_to "#{t('.done')}", complete_task_path(task), data: {method: :put}, class: "btn btn-outline-info btn-sm ml-4 #{activity_btn}" %></td>
    </tr>
  <% end %>

  <% if @completed_tasks.count > 0 %>
    <thead>
    <tr style="background-color: rgba(0,199,0,0.22)">
      <th class="text-center" scope="col">№</th>
      <th class="text-center" scope="col"><%= t('.subj') %></th>
      <th class="text-center" scope="col"><%= t('.hometask') %></th>
      <th class="text-center" scope="col"><%= t('.deadline') %></th>
      <th colspan="3" class="text-center" scope="col"><%= t('.actions') %></th>
      <th class="" scope="col"><%= t('.completed') %></th>
    </tr>
    </thead>
  <% end %>
  <% num = 0 %>
  <% @completed_tasks.each do |task| %>
    <tr class="task">
      <th scope="row"><p style="color:#1f39fb"><%= num += 1%></p></th>
      <td><p style="color:#1f39fb"><s><%= task.subj  %></s></p></td>
      <td><pre style="color:#1f39fb"><s><%= task.descript %></s></pre></td>
      <td class="action "><p style="color:#1f39fb"><s><%= task.deadline %></s></p></td>
      <td><%= link_to "#{t('.show')}", task, class: 'action btn btn-light btn-sm ml-4' %></td>
      <td><%= link_to "#{t('.edit')}", edit_task_path(task), class: "btn btn-outline-warning btn-sm #{activity_btn}" %></td>
      <td><%= link_to "#{t('.delete')}", task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm #{activity_btn}" %></td>
      <td><%= link_to "#{t('.not_done')}", uncomplete_task_path(task), data: {method: :put}, class: "btn btn-outline-info btn-sm ml-4 #{activity_btn}" %></td>
    </tr>
  <% end %>
  </tbody>

</table>

Luchkin_Fedor_IU6_31b_zach_work/app/views/tasks/index_cleared.html.erb
<p id="notice"><%= notice %></p>

<div class="container row sticky-top mt-4" style="top: 90px">
  <h1 class="lert alert bg-warning text-dark col-md-7 " style="height: 80px"> <%= t('tasks.index_cleared.head') %> </h1>
  <% if @cleared_tasks.count > 0 %>
  <% if user_signed_in? %>
    <%= link_to "#{t('.delete_all_done')}", tasks_destroy_all_done_path(@tasks), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-lg col-md-3 ml-1 text-lg-center', style: 'height: 80px; width: 300px' %>
    <% activity_btn = '' %>
  <% else %>
    <p class="alert alert bg-dark text-warning col-md-3"><b><%= t('.login_to') %></b></p>
    <% activity_btn = 'disabled' %>
  <% end %>
</div>


  <table class="table table-hover mb-4 col-md-10">
    <thead>
    <tr style="background-color: rgba(199,0,17,0.22)">
      <th class="text-center" scope="col">№</th>
      <th class="text-center" scope="col"><%= t('.subj') %></th>
      <th class="text-center" scope="col"><%= t('.hometask') %></th>
      <th class="text-center" scope="col"><%= t('.deadline') %></th>
      <th class="text-center" scope="col"><%= t('.completed_at') %></th>
      <th colspan="3" class="text-center" scope="col"><%= t('.actions') %></th>
    </tr>
    </thead>
  <% else %>
    <p class="alert alert bg-dark text-warning col-md-7 font-weight-bold"><%= t('.empty') %></p>
  <% end %>
  <% num = 0 %>
  <tbody>
  <% @cleared_tasks.each do |task| %>
    <tr class="task">
      <th scope="row"><p><%= num += 1%></p></th>
      <td><p><%= task.subj  %></p></td>
      <td><pre><%= task.descript %></pre></td>
      <td class="action "><p><%= task.deadline %></p></td>
      <td><p><%= task.updated_at.in_time_zone('Moscow').strftime("%FT%T")  %></p></td>
      <td><%= link_to "#{t('.edit')}", edit_task_path(task), class: "btn btn-outline-warning btn-sm #{activity_btn}" %></td>
      <td><%= link_to "#{t('.return')}", return_done_task_path(task), method: :put, class: "btn btn-outline-primary btn-sm #{activity_btn}" %></td>
      <td><%= link_to "#{t('.delete')}", task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm #{activity_btn}" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

Luchkin_Fedor_IU6_31b_zach_work/app/views/tasks/index_deadline.html.erb
<p id="notice"><%= notice %></p>

<div class="container row sticky-top mt-4" style="top: 90px">
  <h1 class="alert alert bg-warning text-dark col-md-7 " style="height: 80px"> <%= t('tasks.index_deadline.head') %> </h1>

  <% if user_signed_in? %>
    <%= link_to "#{t('.new_task')}", new_task_path, class: 'btn btn-success btn-lg col-md-3 ml-1 text-lg-center', style: 'height: 80px; width: 300px' %>
    <% activity_btn = '' %>
  <% else %>
    <p class="alert alert bg-dark text-warning col-md-7"><b><%= t('.login_to') %></b></p>
    <% activity_btn = 'disabled' %>
  <% end %>
</div>


<table class="table table-hover mb-4 col-md-8">
  <thead>
  <tr style = "background-color: rgba(255,192,45,1)">
    <th class="text-center">№</th>
    <th class="text-center"><%= t('.subj') %></th>
    <th class="text-center"><%= t('.hometask') %></th>
    <th class="text-center"><%= t('.deadline') %></th>
    <th colspan="3" class="text-center"><%= t('.actions') %></th>
    <th class="ml-2"><%= t('.completed?') %></th>
  </tr>
  </thead>

  <tbody>

    <% num = 0 %>
    <% @uncompleted_tasks.each do |task| %>

      <% if (task.deadline - Date.today) <0 %>
        <% color = '#000000' %>
        <% days =  "#{t('.overdue', count: (task.deadline - Date.today).to_i.abs)}"%>
        <% stilyok = 'font-weight-bold' %>
      <% else %>
        <% days = "#{t('.days', count: (task.deadline - Date.today).to_i.abs)}" %>
        <% if (task.deadline - Date.today) <=3  %>
          <% color = '#b60800' %>
        <% else %>
          <% if (task.deadline - Date.today) <= 10 %>
            <% color = '#ff842b' %>
          <% else %>
            <% color = '#00b200' %>
          <% end %>
        <% end %>
      <% end %>

      <tr class="task">
        <td><p class="<%=stilyok%>" style="color:<%= color %>"><%= num += 1%></p></td>
        <td><p class="<%=stilyok%>" style="color:<%= color %>"><u><%= task.subj  %></u></p></td>
        <td><pre class="<%=stilyok%>" style="color:<%= color %>"> <%= task.descript %></pre></td>
        <td class="action text-center"><p class="<%=stilyok%>" style="color:<%= color %>"><%= (task.deadline - Date.today).to_i.abs %><%= days %></p></td>
        <td><%= link_to "#{t('.show')}", task, class: 'action btn btn-light btn-sm ml-3' %></td>
        <td><%= link_to "#{t('.edit')}", edit_task_path(task), class: "btn btn-outline-warning btn-sm #{activity_btn}" %></td>
        <td><%= link_to "#{t('.delete')}", task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm #{activity_btn}" %></td>
        <td><%= link_to "#{t('.done')}", complete_in_deadline_task_path(task), data: {method: :put}, class: "btn btn-outline-info btn-sm ml-4 #{activity_btn}" %></td>
      </tr>
    <% end %>

  </tbody>
</table>

Luchkin_Fedor_IU6_31b_zach_work/app/views/tasks/index_subj.html.erb
<p id="notice"><%= notice %></p>

<div class="row  sticky-top mt-4 col-md-12" style="top: 90px">
  <h1 class="alert alert bg-warning text-dark col-md-5" style="height: 80px"> <%= t('tasks.index_subj.head') %> </h1>

  <% if user_signed_in? %>
    <%= link_to "#{t('.new_task')}", new_task_path, class: 'btn btn-success btn-lg col-md-S ml-4 text-lg-center', style: 'height: 80px; width: 310px' %>
    <% activity_btn = '' %>
  <% else %>
    <p class="col-md-6"></p>
    <p class="alert alert bg-dark text-warning col-md-6"><b><%= t('.login_to') %></b></p>
    <% activity_btn = 'disabled' %>
  <% end %>
</div>

<table class="table table-hover mb-4 col-md-8">

  <tbody>

  <% num = 0 %>
  <% subj = '' %>
  <% @tasks.each do |task| %>

        <% if (task.deadline - Date.today) <0 %>
          <% color = '#000000' %>
        <% else %>
          <% if (task.deadline - Date.today) <=3  %>
            <% color = '#b60800' %>
          <% else %>
            <% if (task.deadline - Date.today) <= 10 %>
              <% color = '#ff842b' %>
            <% else %>
              <% color = '#00b200' %>
            <% end %>
          <% end %>
        <% end %>

      <% if task.subj == subj %>
        <% if task.status == false %>
          <tr class="task">
            <th scope="row"><p class="" style="color:<%= color %>"><%= num += 1%></p></th>
            <td><pre class="" style="color:<%= color %>"> <%= task.descript %></pre></td>
            <td class="action text-center"><p class="" style="color:<%= color %>"><%= task.deadline %></p></td>
            <td><%= link_to "#{t('.show')}", task, class: 'action btn btn-light btn-sm ml-3' %></td>
            <td><%= link_to "#{t('.edit')}", edit_task_path(task), class: "btn btn-outline-warning btn-sm #{activity_btn}" %></td>
            <td><%= link_to "#{t('.delete')}", task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm #{activity_btn}" %></td>
            <td><%= link_to "#{t('.done')}", complete_in_subj_task_path(task), data: {method: :put}, class: "btn btn-outline-info btn-sm ml-4 #{activity_btn}" %></td>
          </tr>
      <% else %>
        <tr class="task">
          <th scope="row"><p style="color:#1f39fb"><%= num += 1%></p></th>
          <td><pre style="color:#1f39fb"><s><%= task.descript %></s></pre></td>
          <td class="action "><p style="color:#1f39fb"><s><%= task.deadline %></s></p></td>
          <td><%= link_to "#{t('.show')}", task, class: 'action btn btn-light btn-sm ml-3' %></td>
          <td><%= link_to "#{t('.edit')}", edit_task_path(task), class: "btn btn-outline-warning btn-sm #{activity_btn}" %></td>
          <td><%= link_to "#{t('.delete')}", task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm #{activity_btn}" %></td>
          <td><%= link_to "#{t('.not_done')}", uncomplete_in_subj_task_path(task), data: {method: :put}, class: "btn btn-outline-info btn-sm ml-4 #{activity_btn}" %></td>
        </tr>
      <% end %>
        <% else %>
          <% num = 0 %>
          <% subj = task.subj %>

            <tr class="bg" style="top: 50px; background-color:rgba(200,160,0,0.11)">
              <td colspan="7" class="alert-warning bg-warning text-dark text-center font-weight-bolder font-italic">
                <%= subj  %>
              </td>
            </tr>
            <% if task.status == false %>
            <tr class="task">
              <th scope="row"><p class="" style="color:<%= color %>"><%= num += 1%></p></th>
              <td><pre class="" style="color:<%= color %>"> <%= task.descript %></pre></td>
              <td class="action text-center"><p class="" style="color:<%= color %>"><%= task.deadline %></p></td>
              <td><%= link_to "#{t('.show')}", task, class: 'action btn btn-light btn-sm ml-3' %></td>
              <td><%= link_to "#{t('.edit')}", edit_task_path(task), class: "btn btn-outline-warning btn-sm #{activity_btn}" %></td>
              <td><%= link_to "#{t('.delete')}", task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm #{activity_btn}" %></td>
              <td><%= link_to "#{t('.done')}", complete_in_subj_task_path(task), data: {method: :put}, class: "btn btn-outline-info btn-sm ml-4 #{activity_btn}" %></td>
            </tr>
          <% else %>
            <tr class="task">
              <th scope="row"><p style="color:#1f39fb"><%= num += 1%></p></th>
              <td><pre style="color:#1f39fb"><s><%= task.descript %></s></pre></td>
              <td class="action "><p style="color:#1f39fb"><s><%= task.deadline %></s></p></td>
              <td><%= link_to "#{t('.show')}", task, class: 'action btn btn-light btn-sm ml-3' %></td>
              <td><%= link_to "#{t('.edit')}", edit_task_path(task), class: "btn btn-outline-warning btn-sm #{activity_btn}" %></td>
              <td><%= link_to "#{t('.delete')}", task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm #{activity_btn}" %></td>
              <td><%= link_to "#{t('.not_done')}", uncomplete_in_subj_task_path(task), data: {method: :put}, class: "btn btn-outline-info btn-sm ml-4 #{activity_btn}" %></td>
            </tr>
          <% end %>
        <% end %>

  <% end %>
  </tbody>
</table>

Luchkin_Fedor_IU6_31b_zach_work/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-6">
  <h1 class="alert alert bg-warning text-dark mt-3"><%= t('.head') %></h1>
</div>
  <div class="container mt-4 mb-5">
  <p>
    <strong><%= t('.subj') %></strong>
    <%= @task.subj %>
  </p>

  <p>
    <strong><%= t('.descript') %></strong>
    <%= @task.descript %>
  </p>

  <p>
    <strong><%= t('.status') %></strong>
    <%= @task.status %>
  </p>

  <p>
    <strong><%= t('.deadline') %></strong>
    <%= @task.deadline %>
  </p>

  <p>
    <strong><%= t('.hidden') %></strong>
    <%= @task.hidden %>
  </p>

  <% if user_signed_in? %>
    <p>
      <strong><%= t('.email') %></strong>
      <%= @task.user.email %>
    </p>
    <%= link_to "#{t('.edit')}", edit_task_path(@task), class: "btn btn-outline-primary btn-sm col-md-4" %>
  <% end %>
  <%= link_to "#{t('.back')}", tasks_path, class: "btn btn-outline-secondary btn-sm col-md-2" %> <!-- rake routes -> Prefix_path -->
</div>